# Generated by Django 5.2.13 on 2026-05-26 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='media/')),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('consultation_fee', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('hospitalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
