# Generated by Django 5.2.13 on 2026-05-28 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_doctor_consultation_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('payment_status', models.IntegerField(default=0)),
                ('cancel_status', models.IntegerField(default=0)),
                ('refund_status', models.IntegerField(default=0)),
                ('doctorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('h_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('d_id', 'weekday'), name='uniq_doctor_weekday_slot'), models.UniqueConstraint(fields=('d_id', 'slot_date'), name='uniq_doctor_date_slot')],
            },
        ),
    ]
