# Generated by Django 5.2.13 on 2026-05-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_appointment_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=150)),
                ('card_number', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=5)),
                ('expiry_year', models.IntegerField()),
                ('expiry_month', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('currentdate', models.DateField(auto_now_add=True)),
                ('appointmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
