# Generated by Django 5.2.13 on 2026-05-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_payment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('cancel_status', 0)), fields=('doctorid', 'date', 'time'), name='uniq_active_doctor_date_time'),
        ),
    ]
