# Generated by Django 5.2.13 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(default='Service', max_length=30),
        ),
    ]
